# Development Dockerfile
FROM node:lts-alpine 

# Make  working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy application files
COPY . .

# Expose port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start:dev"]

